// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJcRlY4EViSx5Pa9ni2vQT7aYI5-fEJw8',
    appId: '1:291128080266:web:c793dab4a363a7a2077a73',
    messagingSenderId: '291128080266',
    projectId: 'instagram-clone-5e89b',
    authDomain: 'instagram-clone-5e89b.firebaseapp.com',
    storageBucket: 'instagram-clone-5e89b.firebasestorage.app',
    measurementId: 'G-3VWYPPW8MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6T9h65CnPyW9osp1oqYDsubARRTMNEMg',
    appId: '1:291128080266:android:9773844e6c2489e2077a73',
    messagingSenderId: '291128080266',
    projectId: 'instagram-clone-5e89b',
    storageBucket: 'instagram-clone-5e89b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKcVb3bRy_H8z-9m1G5YpWnOEftfm4h_U',
    appId: '1:291128080266:ios:f04c29267644fd34077a73',
    messagingSenderId: '291128080266',
    projectId: 'instagram-clone-5e89b',
    storageBucket: 'instagram-clone-5e89b.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKcVb3bRy_H8z-9m1G5YpWnOEftfm4h_U',
    appId: '1:291128080266:ios:f04c29267644fd34077a73',
    messagingSenderId: '291128080266',
    projectId: 'instagram-clone-5e89b',
    storageBucket: 'instagram-clone-5e89b.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJcRlY4EViSx5Pa9ni2vQT7aYI5-fEJw8',
    appId: '1:291128080266:web:dc90018cec4edb86077a73',
    messagingSenderId: '291128080266',
    projectId: 'instagram-clone-5e89b',
    authDomain: 'instagram-clone-5e89b.firebaseapp.com',
    storageBucket: 'instagram-clone-5e89b.firebasestorage.app',
    measurementId: 'G-TYQRNRH23M',
  );
}
